# Generated by Django 4.1.6 on 2023-02-27 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0004_rename_users_movie_user_alter_movie_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="user",
        ),
        migrations.AddField(
            model_name="movie",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
