# Generated by Django 4.1.6 on 2023-02-27 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_remove_movie_user_movie_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movieorder",
            name="buyed_by",
        ),
    ]
